### ISSUE TITLE
DocStringsExtensions v0.9

### ISSUE THREAD

**Issue by bjarthur** [JuliaStats/KernelDensity.jl#106]
Gadfly got a [CompatHelper PR](https://github.com/GiovineItalia/Gadfly.jl/pull/1586) for DocStringsExtensions v0.9, but the [CI fails](https://github.com/GiovineItalia/Gadfly.jl/runs/6640065806?check_suite_focus=true) because [KernelDensity requires 0.8](https://github.com/JuliaStats/KernelDensity.jl/blob/master/Project.toml).  what i don't understand is why KernelDensity did not also get a similar PR.  happy to submit a manual PR to the same effect.

**Comment by dehann** [comment]
Issue seems to be CompatHelper workflow was automatically paused after 60 day timer.  Just needs to be re-enabled.

**Comment by tpapp** [comment]
Should be fixed by #107.
