### ISSUE TITLE
Feature Request: Mode(s) finding

### ISSUE THREAD

**Issue by bdeonovic** [JuliaStats/KernelDensity.jl#11]
It would be great to have an implementation of an algorithm that finds modes of kernel density estimates. Most common algorithm is mean-shift algorithm:

Comaniciu, Dorin; Peter Meer (May 2002). "Mean Shift: A Robust Approach Toward Feature Space Analysis". IEEE Transactions on Pattern Analysis and Machine Intelligence (IEEE) 24 (5): 603–619. doi:10.1109/34.1000236.

A great short (2 page) guide to using mean shift algorithm for clustering http://homepages.inf.ed.ac.uk/rbf/CVonline/LOCAL_COPIES/TUZEL1/MeanShift.pdf

Might be more appropriate for the Clustering.jl package.

**Comment by simonbyrne** [comment]
I think it would be useful to have in this package, though I don't really have time to do it myself in the near future. If you want to open a pull request, I'd be happy to look over it.

**Comment by bdeonovic** [comment]
I made a pull request for this at Clustering.jl (https://github.com/JuliaStats/Clustering.jl/pull/43). If people want to find peaks of a kernel density estimate they can use the code there.
