### ISSUE TITLE
Key for densities in plot?

### ISSUE THREAD

**Issue by JonathanGallagher** [JuliaStats/KernelDensity.jl#18]
Is there a way to plot a legend off to the side of the image that shows what the colours from blue to red mean, as in:
![qpgm6](https://cloud.githubusercontent.com/assets/5176124/8608645/01c72aaa-265a-11e5-9412-aa0f64d67b3b.png)

**Comment by simonbyrne** [comment]
Plotting has moved to https://github.com/JuliaPlots/StatPlots.jl: if this is still an issue, could you reopen there?
