### ISSUE TITLE
Mass point to the right in the estimated density

### ISSUE THREAD

**Issue by pkofod** [JuliaStats/KernelDensity.jl#21]
I am not sure if this is a bug, or my ignorance but running

```julia
using Distributions
using Gadfly
using KernelDensity


n = 300
dx = rand(TruncatedNormal(1., 20., 0, Inf),n)
x = cumsum(dx)

dx_kde = kde(dx)
dx_kde_midpoints = kde(dx, minimum(dx):maximum(dx)*2)

plot(x=1:n, y=x, Geom.line)
plot(x = dx_kde.x, y = dx_kde.density,Geom.line)
plot(x = dx_kde_midpoints.x, y = dx_kde_midpoints.density, Geom.line)
```

Gives the following two plots (in the same order as the code)

![nomid](https://cloud.githubusercontent.com/assets/8431156/9895772/58e3ed00-5c01-11e5-91e1-d749704d41d9.png)
![midpoints](https://cloud.githubusercontent.com/assets/8431156/9895774/5cd655ba-5c01-11e5-8fbe-f24ec2761b82.png)

I really just wanted to truncate it to the left, which seems to work. No matter how high or low I set the upper limit in the `kde(Array, Range)` call, I get that jump in the end.

**Comment by simonbyrne** [comment]
See https://github.com/JuliaStats/KernelDensity.jl/issues/12#issuecomment-90646652

**Comment by pkofod** [comment]
Ah, okay, so I am basically seemingly the probability i remove to the left being added to the right. I get it
