### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ranjanan** [JuliaStats/KernelDensity.jl#30]
Tests have deprecation warnings on 0.1.2, but don't on master (Julia v0.5). Could you please tag a new release?

**Comment by tkelman** [comment]
0.1.2 and master are identical
```
$ cat KernelDensity/versions/0.1.2/sha1
48cfa6aec1acb6de62b2aee547281293a298eeef
```

**Comment by ranjanan** [comment]
Ah, I see. I got a deprecation warning the first time I did `Pkg.test`, because of [this line].(https://github.com/JuliaStats/KernelDensity.jl/blob/master/src/KernelDensity.jl#L21). `Pkg.checkout` made it go away, so I posted this issue here. 
```
WARNING: symbol is deprecated, use Symbol instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in symbol(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in @glue(::Any) at /Users/ranjan/.julia/v0.5/KernelDensity/src/KernelDensity.jl:21
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /Users/ranjan/.julia/v0.5/KernelDensity/src/KernelDensity.jl, in expression starting on line 28
```

**Comment by ranjanan** [comment]
Interestingly, after `Pkg.free` and `Pkg.test` I'm not able to reproduce this.

**Comment by ranjanan** [comment]
Ah, wait, I get this warning during precompilation. That's why the first `Pkg.add` gave me that warning.

**Comment by tkelman** [comment]
Looks like it depends on whether or not you have PyPlot or Winston installed. That `@glue` macro has the same precompilation issue that Requires.jl does, and should probably be replaced with something that uses whatever the small piece of Plots.jl or RecipesWhatever you're supposed to use now.

**Comment by ranjanan** [comment]
What does this have to do with PyPlot or Winston? I didn't understand your comparison. 

I think just putting `@compat Symbol` in that line would fix this.

**Comment by tkelman** [comment]
Look at what the macros' used for. https://github.com/JuliaStats/KernelDensity.jl/blob/48cfa6aec1acb6de62b2aee547281293a298eeef/src/KernelDensity.jl#L28-L29

If this package did plotting in a more modern precompilation-compatible way it wouldn't need to define that macro at all.

**Comment by ranjanan** [comment]
Oh okay. So, do you think a refactor of this package to use Plots instead is required?

**Comment by tkelman** [comment]
For it to properly be precompile-compatible (and therefore for any other packages that depend on this one to be correctly precompile-compatible), yes. But at the moment you could just fix the deprecation.

**Comment by ararslan** [comment]
I'd be in favor of removing the plotting stuff from here entirely. If it belongs anywhere I would think it'd be StatPlots. At the very least we could just give an example in the readme or whatever on how to plot if a plotting package is available.

**Comment by tkelman** [comment]
It looks like StatPlots depends on this package, so that sounds ideal.

**Comment by ranjanan** [comment]
@ararslan Shall I put together a PR removing plotting entirely then?

**Comment by ararslan** [comment]
@ranjanan Sure, if you want to then go for it. 👍 I can do it if you'd rather not.

**Comment by tlnagy** [comment]
Hey @ranjanan, did you have time to get that PR together?

**Comment by ararslan** [comment]
He did indeed: https://github.com/JuliaStats/KernelDensity.jl/pull/31 😄

**Comment by ranjanan** [comment]
Now that #31 has merged, can we tag a new release please?

**Comment by ararslan** [comment]
Sure, will do.
