### ISSUE TITLE
remove dependency on deprecated package Grid

### ISSUE THREAD

**Issue by shashi** [JuliaStats/KernelDensity.jl#34]
From Grid.jl readme:

> **Note**: for interpolation, the successor to Grid is [Interpolations](https://github.com/tlycken/Interpolations.jl). Julia 0.5 will be the last supported release for Grid.

**Comment by tlnagy** [comment]
This would be helpful for unbreaking Gadfly tests on julia master

**Comment by tlnagy** [comment]
Thanks! Could you tag a new release?

**Comment by simonbyrne** [comment]
Just done: https://github.com/JuliaLang/METADATA.jl/pull/6111

**Comment by tlnagy** [comment]
Thanks!
