### ISSUE TITLE
Add plot recipes?

### ISSUE THREAD

**Issue by tbreloff** [JuliaStats/KernelDensity.jl#35]
Looking at https://github.com/JuliaStats/KernelDensity.jl/commit/2de1e7bae939d923cbfd4fb000921aca42d1a6fb it seems like it would be pretty straightforward to add recipe(s) so that all these plots are supported easily.  Would you rather add a dependency on RecipesBase here and keep the recipes close, or add to StatPlots?  We can choose either since StatPlots depends on this package.

**Comment by simonbyrne** [comment]
I don't really mind: I guess since it's already a dependency, you might as well move them to StatPlots.

**Comment by tbreloff** [comment]
Ok done.  https://github.com/JuliaPlots/StatPlots.jl/commit/897ee05dbec5a66207e168e6065390c7078205fe

**Comment by tbreloff** [comment]
If you want to give a short example I can add it to the StatPlots readme

**Comment by tbreloff** [comment]
Something like:

```julia
using StatPlots
k = # make a KDE object
surface(k)
```
