### ISSUE TITLE
Should probably import kde from Distributions

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/KernelDensity.jl#38]

**Comment by ararslan** [comment]
The only mention of `kde` in Distributions is [here](https://github.com/JuliaStats/Distributions.jl/blob/bcadc16f8955733e36c7c978901efea5dff7aa14/src/Distributions.jl#L191), where a comment says that it's actually coming from Stats.jl (which shouldn't even be installable anymore). As such it might make more sense to remote that mysterious `export` from Distributions and just defined `kde` here.

**Comment by andreasnoack** [comment]
The idea with having these definitions upstream is that several implementations can import it. If we move it to `KernelDensity` then other kernel density implementatinos would need to depend on `KernelDensity`. Maybe we want that maybe we won't. Can you find separate uses of `kde`?

**Comment by ararslan** [comment]
Based on a brief GitHub search, there are at least two packages that define their own `kde` without using KernelDensity.jl: [KernelDensityEstimate.jl](https://github.com/dehann/KernelDensityEstimate.jl) (registered), [KernelEstimator.jl](https://github.com/panlanfeng/KernelEstimator.jl) (registered) and [ABCAuction.jl](https://github.com/mcreel/ABCAuction.jl) (unregistered). The latter two depend on Distributions.jl but the first does not.

**Comment by matbesancon** [comment]
to close? cc @andreasnoack

**Comment by andreasnoack** [comment]
Probably okay

**Comment by matbesancon** [comment]
seems reasonable to define `kde` in here, people which want to define their own can import it
