### ISSUE TITLE
accessors for gridpoints and corresponding densities

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/KernelDensity.jl#67]
It is unclear if eg for univariate densities the slots `x` and `density` can be used (ie are part of the API and can be expected to be stable, not an internal implementation detail).

It would be great to document this, or alternatively provide accessor functions. Similarly for bivariate.

If the package maintainers clarify their intention, I would be happy to make a PR.

**Comment by tpapp** [comment]
Could also help with #66.

**Comment by tpapp** [comment]
Bump --- can anyone clarify this?

**Comment by tpapp** [comment]
@simonbyrne , can you help me with this? Again, I just need a decision on what would be preferred, happy to make the PR.

**Comment by tlnagy** [comment]
This package would benefit greatly from these accessors and a tutorial. I would prefer to have documented functions for access to prevent breakage if internals get moved around.

**Comment by simonbyrne** [comment]
I'm afraid I don't have the bandwidth to contribute to this repository for the forseeable future. @tpapp and @tlnagy I've added you as collaborators, please do as you see fit.

**Comment by simonbyrne** [comment]
Yes, check https://github.com/JuliaStats/KernelDensity.jl/invitations
